server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # SPA-Routing
    }

    # In Produktion übernimmt Traefik das /api-Routing,
    # diese Regel ist nur als Fallback drin
    location /api {
        proxy_pass http://192.168.0.230:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
