- name: Rollback VM to clean-base snapshot
  community.general.proxmox_snap:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    vmid: "{{ vmid }}"
    snapname: "{{ start_snapshot }}"
    state: rollback
  delegate_to: localhost