- name: Ensure temp dir exists
  ansible.windows.win_file:
    path: C:\temp
    state: directory

- name: Setup kopieren
  ansible.windows.win_command: >
    curl -L -o "c:\temp\setup-al.zip"  "http://192.168.0.224:8081/artifactory/ui/artifactactions/downloadfolder?repoKey=dataal-dev-generic-local&path=data/develop/Install-Build-499&archiveType=zip&includeChecksumFiles=false"
  
- name: Setup entpacken
  ansible.windows.win_command: >
    powershell -Command "Expand-Archive -Path 'c:\temp\setup-al.zip' -DestinationPath 'c:\temp\setup-al' -Force"

- name: Setup installieren
  ansible.windows.win_package:
    path: C:\temp\setup-al\setup.exe
    arguments: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    expected_return_code: [0, 3010]

